[2025-06-27T07:35:22.975+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:35:22.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:35:23.171+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:35:23.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:35:23.858+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:35:23.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:35:23.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:35:25.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 2.831 seconds
[2025-06-27T07:37:29.102+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:37:29.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:37:29.120+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:37:29.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:37:29.344+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:37:29.290+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:37:29.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:37:29.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.405 seconds
[2025-06-27T07:38:06.270+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:06.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:38:06.292+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:38:06.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:06.432+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:38:06.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:38:06.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:06.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.306 seconds
[2025-06-27T07:38:36.990+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:36.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:38:37.012+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:38:37.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:37.121+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:38:37.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:38:37.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:38:37.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.348 seconds
[2025-06-27T07:39:11.195+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:11.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:39:11.210+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:39:11.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:11.341+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:39:11.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:39:11.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:11.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.380 seconds
[2025-06-27T07:39:46.467+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:46.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:39:46.481+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:39:46.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:46.608+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:39:46.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:39:46.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:39:46.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.289 seconds
[2025-06-27T07:40:18.060+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:18.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:40:18.075+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:40:18.073+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:18.176+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:40:18.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:40:18.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:18.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.390 seconds
[2025-06-27T07:40:48.870+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:48.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:40:48.889+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:40:48.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:49.014+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:40:48.992+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:40:49.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:40:49.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.331 seconds
[2025-06-27T07:41:20.987+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:20.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:41:20.999+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:41:20.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:21.101+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:41:21.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:41:21.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:21.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.236 seconds
[2025-06-27T07:41:55.076+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:55.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:41:55.135+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:41:55.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:55.773+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:41:55.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:41:55.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:41:55.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.928 seconds
[2025-06-27T07:42:44.507+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:42:44.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:42:44.517+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:42:44.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:42:44.594+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:42:44.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:42:44.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:42:44.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.185 seconds
[2025-06-27T07:43:17.537+0000] {processor.py:186} INFO - Started process (PID=791) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:17.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:43:17.556+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:43:17.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:17.678+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:43:17.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:43:17.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:17.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.328 seconds
[2025-06-27T07:43:48.753+0000] {processor.py:186} INFO - Started process (PID=854) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:48.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:43:48.762+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:43:48.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:48.818+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:43:48.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:43:48.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:43:48.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.141 seconds
[2025-06-27T07:44:19.484+0000] {processor.py:186} INFO - Started process (PID=918) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:19.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:44:19.492+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:44:19.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:19.550+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:44:19.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:44:19.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:19.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.130 seconds
[2025-06-27T07:44:50.206+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:50.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:44:50.214+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:44:50.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:50.257+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:44:50.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:44:50.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:44:50.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.120 seconds
[2025-06-27T07:45:20.731+0000] {processor.py:186} INFO - Started process (PID=1045) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:20.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:45:20.740+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:45:20.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:20.817+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:45:20.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:45:20.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:20.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.166 seconds
[2025-06-27T07:45:51.173+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:51.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:45:51.182+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:45:51.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:51.271+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:45:51.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:45:51.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:45:51.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.178 seconds
[2025-06-27T07:46:21.695+0000] {processor.py:186} INFO - Started process (PID=1168) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:21.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:46:21.702+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:46:21.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:21.754+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:46:21.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:46:21.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:21.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.123 seconds
[2025-06-27T07:46:52.343+0000] {processor.py:186} INFO - Started process (PID=1231) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:52.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:46:52.356+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:46:52.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:52.428+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:46:52.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:46:52.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:46:52.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.166 seconds
[2025-06-27T07:47:22.802+0000] {processor.py:186} INFO - Started process (PID=1294) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:22.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:47:22.810+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:47:22.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:22.858+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:47:22.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:47:22.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:22.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.117 seconds
[2025-06-27T07:47:53.390+0000] {processor.py:186} INFO - Started process (PID=1357) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:53.392+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:47:53.396+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:47:53.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:53.449+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:47:53.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:47:53.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:47:53.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.117 seconds
[2025-06-27T07:48:23.892+0000] {processor.py:186} INFO - Started process (PID=1420) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:23.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:48:23.900+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:48:23.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:23.963+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:48:23.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:48:23.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:24.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.136 seconds
[2025-06-27T07:48:54.667+0000] {processor.py:186} INFO - Started process (PID=1483) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:54.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:48:54.675+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:48:54.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:54.766+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:48:54.746+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:48:54.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:48:54.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.177 seconds
[2025-06-27T07:51:58.411+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:51:58.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:51:58.451+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:51:58.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:51:58.667+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:51:58.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:51:58.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:51:58.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.511 seconds
[2025-06-27T07:52:36.335+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:52:36.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:52:36.373+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:52:36.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:52:37.070+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:52:36.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:52:37.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:52:37.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 1.477 seconds
[2025-06-27T07:53:08.168+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:08.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:53:08.173+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:53:08.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:08.217+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:53:08.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:53:08.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:08.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.093 seconds
[2025-06-27T07:53:38.922+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:38.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:53:38.944+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:53:38.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:39.036+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:53:39.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:53:39.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:53:39.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.275 seconds
[2025-06-27T07:54:09.443+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:09.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:54:09.452+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:54:09.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:09.520+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:54:09.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:54:09.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:09.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.165 seconds
[2025-06-27T07:54:39.715+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:39.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:54:39.725+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:54:39.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:39.770+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:54:39.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:54:39.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:54:39.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.110 seconds
[2025-06-27T07:55:10.061+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:55:10.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:55:10.069+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:55:10.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:55:10.129+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:55:10.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:55:10.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:55:10.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.148 seconds
[2025-06-27T07:59:25.782+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:59:25.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T07:59:25.812+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:59:25.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:59:25.936+0000] {logging_mixin.py:190} INFO - [2025-06-27T07:59:25.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T07:59:25.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T07:59:26.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.447 seconds
[2025-06-27T08:00:01.449+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:01.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:00:01.466+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:00:01.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:01.644+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:00:01.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:00:01.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:01.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.387 seconds
[2025-06-27T08:00:57.889+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:57.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:00:57.933+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:00:57.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:58.086+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:00:58.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:00:58.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:00:58.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.349 seconds
[2025-06-27T08:01:29.125+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:29.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:01:29.142+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:01:29.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:29.246+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:01:29.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:01:29.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:29.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.258 seconds
[2025-06-27T08:01:59.645+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:59.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:01:59.653+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:01:59.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:59.691+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:01:59.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:01:59.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:01:59.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.097 seconds
[2025-06-27T08:02:30.355+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:02:30.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:02:30.362+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:02:30.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:02:30.408+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:02:30.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:02:30.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:02:30.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.104 seconds
[2025-06-27T08:03:00.784+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:00.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:03:00.791+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:03:00.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:00.835+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:03:00.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:03:00.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:00.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.103 seconds
[2025-06-27T08:03:31.241+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:31.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:03:31.248+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:03:31.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:31.294+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:03:31.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:03:31.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:03:31.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.114 seconds
[2025-06-27T08:04:01.554+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:01.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:04:01.566+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:04:01.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:01.605+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:04:01.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:04:01.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:01.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.105 seconds
[2025-06-27T08:04:32.671+0000] {processor.py:186} INFO - Started process (PID=613) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:32.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:04:32.684+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:04:32.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:32.790+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:04:32.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:04:32.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:04:32.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.246 seconds
[2025-06-27T08:05:03.850+0000] {processor.py:186} INFO - Started process (PID=677) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:03.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:05:03.960+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:05:03.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:04.176+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:05:04.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:05:04.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:04.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.656 seconds
[2025-06-27T08:05:35.385+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:35.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:05:35.406+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:05:35.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:35.558+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:05:35.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:05:35.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:05:35.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.333 seconds
[2025-06-27T08:06:06.942+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:06:06.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/driven_data_pipeline.py for tasks to queue
[2025-06-27T08:06:06.955+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:06:06.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:06:07.012+0000] {logging_mixin.py:190} INFO - [2025-06-27T08:06:06.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/driven_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/driven_data_pipeline.py", line 6, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-06-27T08:06:07.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/driven_data_pipeline.py
[2025-06-27T08:06:07.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/driven_data_pipeline.py took 0.143 seconds
